### PR TITLE
Achieve Carthage compatibility by compiling source file in target's build phase

### PR DESCRIPTION
**Pull request by tforzaglia**
Hey, @bahlo 

Great framework here! Very useful for an app I'm working on. I'm using Carthage in my app and was unfortunately having a problem with integrating SwiftGif. Based on #48, it seems that others have also had similar problems with using Carthage to integrate SwiftGif.

Anyway, this PR should fix the issue. Feel free to test it out and merge if you like.

### CODE REVIEW

**Comment by tomorrowkey** [comment]
Is there any problem to merge?

**Comment by tforzaglia** [comment]
@tomorrowkey, this is all good to merge from my point of view, but as this repository belongs to @bahlo, he will need to evaluate and merge if he satisfied with my pull request.

**Comment by bahlo** [comment]
Thank you very much!

**Comment by tanukiti1987** [comment]
@bahlo Thank you 👍 Is there the plan to release new version at CocoaPods and Carthage?

**Comment by jgs0** [comment]
I had the same problem last week. Everything up date, I gues: 

github "bahlo/SwiftGif" >= 1.6.1
xcodebuild -version
Xcode 10.1
Build version 10B61

The Framework is build but it seamse to be empty... as a fix  I just use the modulefile source directly.

**Pull request merged**
