### PR TITLE
Add a gifData property

### PR DESCRIPTION
**Pull request by zhouhao27**
Add a property for gif data in case we need to retrieve it back sometime.

### CODE REVIEW

**Comment by bahlo** [comment]
What's the use case for this?

**Comment by zhouhao27** [comment]
@bahlo Sometimes we may need to retrieve the gif data back. For example, I'm using a social API which is able to send data. I could get the gif data in UIImage+Gif and then send to the Social API.

**Comment by bahlo** [comment]
This will take place in the next minor version, thank you for your PR! 👍

**Comment by yzhong52** [comment]
The use case is too specific, I am not sure if we should add it to `UIImage`.

**Comment by bahlo** [comment]
I agree. Thanks anyways @yzhong52 and sorry for the big delay

**Pull request closed without merging**
